# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('observacion', models.TextField()),
                ('estado', models.BooleanField(default=False, help_text='Un libro es considerado de Referencia si')),
                ('sw_tolerancia_acumulada', models.BooleanField(default=True, help_text='Trabajar con el modo de tolerancia acumulada')),
                ('tolerancia_acumulada', models.IntegerField()),
            ],
        ),
    ]
