# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignacionHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DesignacionPermiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_ini', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Feriados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HorarioRango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('rango_entrada_ini', models.TimeField()),
                ('rango_entrada_fin', models.TimeField()),
                ('rango_salida_ini', models.TimeField()),
                ('rango_salida_fin', models.TimeField()),
                ('tolerancia_individual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('uid', models.CharField(max_length=50)),
                ('biometrico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='horario',
            name='estado',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado',
            field=models.BooleanField(default=False, help_text='El usuario esta activo en el sistema'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='registrohorario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_personal.Funcionario'),
        ),
        migrations.AddField(
            model_name='horariorango',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_personal.Horario'),
        ),
        migrations.AddField(
            model_name='designacionpermiso',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_personal.Funcionario'),
        ),
        migrations.AddField(
            model_name='designacionpermiso',
            name='tipo_permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_personal.TipoPermiso'),
        ),
        migrations.AddField(
            model_name='designacionhorario',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_personal.Funcionario'),
        ),
        migrations.AddField(
            model_name='designacionhorario',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_personal.Horario'),
        ),
    ]
