# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_personal', '0002_auto_20160502_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feriados',
            new_name='Feriado',
        ),
    ]
