# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_personal', '0003_auto_20160503_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariorango',
            name='tolerancia_individual',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
