# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_personal', '0009_auto_20160504_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='designacionpermiso',
            name='aprobado',
            field=models.BooleanField(choices=[(True, 'Aprobado'), (False, 'No Aprobado')], default=False),
        ),
        migrations.AddField(
            model_name='designacionpermiso',
            name='jefe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jefe', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
