# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_personal', '0010_auto_20160504_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='designacionpermiso',
            name='token_mail',
            field=models.CharField(default='abcd', max_length=250),
            preserve_default=False,
        ),
    ]
