# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_personal', '0011_designacionpermiso_token_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='designacionpermiso',
            name='token_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
