# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_personal', '0012_designacionpermiso_token_confirmation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designacionpermiso',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
